#
# Module manifest for module 'DockerProvider'
#
# Generated by: johnstep
#
# Generated on: 09/13/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'DockerProvider.psm1'

# Version number of this module.
ModuleVersion = '0.0.0.3'

# ID used to uniquely identify this module
GUID = 'f8dfd4ee-8d92-484d-9813-9cf454f0d23f'

# Author of this module
Author = 'johnstep'

# Company or vendor of this module
CompanyName = 'Docker'

# Copyright statement for this module
Copyright = '(c) 2017 Docker, Inc. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module with commands for discovering, installing, and updating Docker images.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Functions to export from this module
FunctionsToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    "PackageManagementProviders" = 'DockerProvider.psm1'

    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PackageManagement', 'Provider')
        ProjectUri = 'https://github.com/johnstep/OneGet-MicrosoftDockerProvider'
        LicenseUri = 'https://github.com/johnstep/OneGet-MicrosoftDockerProvider/blob/developer/LICENSE'
        ReleaseNotes = @'
- Docker Provider to find, save and install docker on windows.
'@
    } # End of PSData hashtable

} # End of PrivateData hashtable
}
